#!/bin/sh

# ping -o means return success on first good ping
# ping -c 3 means ping at most three times
net=${1:-localhost}
if ping -oc 3 ${net} 2>/dev/null >/dev/null
then
  echo "OK network can reach ${net}"
  exit 0
else
  echo "FAIL network cannot reach ${net}"
  exit 2
fi

